### ISSUE TITLE
Cannot find module 'NodeApiHelpers'

### ISSUE THREAD

**Issue by lmmsoft** [almtcger/VstsExtensions#1]
Hi,

When use Build Quality Checks
I had error : "Unhandled: Cannot find module 'NodeApiHelpers' ". 
I tried to use " sudo npm install  -g api-helpers" , but it doesn't work.
I am running it on a ubuntu 16.04 machine. npm version 3.5.2

Error log:
```
=============================================================================
Task         : Build Quality Checks
Description  : Breaks a build based on quality metrics like number of warnings or code coverage.
Version      : 2.5.0
Author       : Microsoft Premier Services
Help         : [Docs](https://github.com/almtcger/VstsExtensions/blob/master/BuildQualityChecks/en-US/overview.md)
==============================================================================
Unhandled: Cannot find module 'NodeApiHelpers'
```

**Comment by almtcger** [comment]
Hi Immsoft,

I'm very sorry for the late response! We rarely check the GitHub repo as it only contains our documentation and we usually handle support through our support mail address. Does the issue still exist with the latest version (2.6.2) of the task?

The NodeApiHelpers module is bundled with the task. Please take a look at the folder _tasks/BuildQualityChecks_16a2ad20-f191-11e5-bed4-ab22bcd17937/2.6.2/node_modules inside your agent's working folder. It should contain a folder named nodeapihelpers.

If that folder exists and you're still running into the issue, please set the environment variable NODE_DEBUG to the value "module" (without quotes), restart the build agent, run the build again and send us the log files to our support mail address [PSGerExtSupport@microsoft.com](mailto:PSGerExtSupport@microsoft.com).

**Comment by Seidel-Michael** [comment]
Same issue here.
I've sent a message to the support address.

**Comment by almtcger** [comment]
We found the root cause for this issue to be incorrect casing of module imports that work on Windows but not on Linux. We will release a fixed version of the task today.
