### ISSUE TITLE
Drop Down Menu for Selecting Baseline Build Def Broken

### ISSUE THREAD

**Issue by Cartwheel4** [almtcger/VstsExtensions#3]
When you click on the drop down menu for selecting the baseline build definition it spins for about 30 seconds and fails with a 404 response from the server.

**Comment by Cartwheel4** [comment]
This is the build def that it reproduces on: 

[https://microsoft.visualstudio.com/Universal%20Store/_apps/hub/ms.vss-ciworkflow.build-ci-hub?_a=edit-build-definition&id=11487](url)

**Comment by almtcger** [comment]
This issue is fixed with the newest version of the task.
