### ISSUE TITLE
Does warning policy based on previous value work?

### ISSUE THREAD

**Issue by koshdim** [almtcger/VstsExtensions#6]
Hi

Is warning policy based on previous value supported already?
Build Quality Checks shows correct, non zero, increased number of warnings in my build, but it doesn't fail the build.

**Comment by almtcger** [comment]
Hi koshdim,

the feature is fully implemented and should work. Could you run your build again with the variable **System.Debug** set to **true** and send me the log from the BuildQualityChecks task to PSGerExtSupport@microsoft.com? I'll have a look and can hopefully spot the issue quickly.

Thanks
René

**Comment by koshdim** [comment]
thanks for quick response!

I made it to work by putting "Check Build Quality" task after all build tasks. 
Debug log of the situation when it is in between building two solutions I emailed to address you mentioned, I guess it might be valuable to you.

Tak!
Dmytro

**Comment by almtcger** [comment]
We're closing this issue as it seems to be resolved.
